In [35]:
# Laurent LEQUIEVRE
# Research Engineer, CNRS (France)
# Institut Pascal UMR6602
# laurent.lequievre@uca.fr

In [36]:
# torch.nn contains loss functions

import torch
import torch.nn as nn

In [37]:
import sys

#print python version
print('__python version:', sys.version)

# print torch version
print('__torch version:', torch.__version__)

# print if cuda is available (True or False)
print('__cuda is available:', torch.cuda.is_available())

# print cuda informations
print('__cuda version :', torch.version.cuda)
print('__number cuda devices:', torch.cuda.device_count())
print ('__available devices ', torch.cuda.device_count())
print ('__current cuda device ', torch.cuda.current_device())

__python version: 3.5.2 (default, Oct  7 2020, 17:19:02) 
[GCC 5.4.0 20160609]
__torch version: 1.5.1
__cuda is available: True
__cuda version : 10.2
__number cuda devices: 1
__available devices  1
__current cuda device  0


In [38]:
my_device = torch.device("cuda") # can be also "cpu"
my_dtype = torch.float

# Create random Tensors

# This returns a tensor of size 3 × 5
# filled with values from standard normal distribution, that is mean is 0 and variance is 1.
# Setting requires_grad=True indicates that we want to compute gradients during the backward pass.
input = torch.randn(3, 5, device=my_device, dtype=my_dtype, requires_grad=True) 

target = torch.randn(3, 5, device=my_device, dtype=my_dtype)

print('input: ', input)
print('target: ', target)

input:  tensor([[-0.2847, -1.8747,  1.2070, -0.4012,  0.6107],
        [ 1.5438,  1.4165, -0.3873, -1.0945, -0.4519],
        [ 1.7299, -0.5388, -0.3043,  1.0659,  0.8976]], device='cuda:0',
       requires_grad=True)
target:  tensor([[-0.2769, -0.2305,  0.0025, -0.6237,  2.0353],
        [ 1.2126,  0.4152, -0.4625, -0.6712, -0.6937],
        [-0.9768, -0.1945,  1.5002, -0.9801,  0.9110]], device='cuda:0')


In [39]:
# Get size of tensors input and target
print("input size={}, target size={}".format(input.shape,target.shape))

input size=torch.Size([3, 5]), target size=torch.Size([3, 5])


In [40]:
input.grad
# If x is a Tensor that has x.requires_grad=True then x.grad is another Tensor holding the gradient of x 
# with respect to some scalar value.
# No value actually !

In [41]:
mae_loss = nn.L1Loss() # Define a loss function : The Mean Absolute Error (MAE)
loss = mae_loss(input, target) # Apply the loss function to input and target
print('loss value : ', loss)

loss value :  tensor(0.8994, device='cuda:0', grad_fn=<L1LossBackward>)


loss.backward() computes dloss/dx for every parameter x which has requires_grad=True. 
These are accumulated into x.grad for every parameter x. In pseudo-code: x.grad += dloss/dx

optimizer.step updates the value of x using the gradient x.grad. 
For example, the SGD optimizer performs:
(lr = learning rate)

x += -lr * x.grad

optimizer.zero_grad() clears x.grad for every parameter x in the optimizer. 

It’s important to call this before loss.backward(), otherwise you’ll accumulate the gradients from multiple passes.

If you have multiple losses (loss1, loss2) you can sum them and then call backwards once:

loss3 = loss1 + loss2
loss3.backward()

In [42]:
loss.backward() # compute the gradient of input tensor (the only one with requires_grad=True)

In [43]:
# Get gradient of tensor input saved in a field named grad.
input.grad

tensor([[-0.0667, -0.0667,  0.0667,  0.0667, -0.0667],
        [ 0.0667,  0.0667,  0.0667, -0.0667,  0.0667],
        [ 0.0667, -0.0667, -0.0667,  0.0667, -0.0667]], device='cuda:0')

In [44]:
input.grad.zero_() # Manually zero the input gradient

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0')

In [45]:
input.grad

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0')

In [46]:
# Just to verify torch matmul properties
# see : The difference between torch.mul, torch.mm, torch.bmm, torch.matmul
# https://www.programmersought.com/article/80074664295/

import torch

x = torch.randn(2, 1) # torch.Size([2, 1])
A = torch.randn(1, 1) # torch.Size([1, 1])
b = torch.randn(1) # torch.Size([1])

# torch matmul -> If both arguments are 2-dimensional, the matrix-matrix product is returned.
result = torch.matmul(x,A) # torch.Size([2, 1])

print("x={}, A={}".format(x,A))
print("torch.matmul(x,A)={}, nb elem={}".format(result,result.numel()))
print("b={}".format(b))
result2 = result + b # torch.Size([2, 1])
print("torch.matmul(x,A)+b={}".format(result2))

x=tensor([[-0.3129],
        [ 1.5263]]), A=tensor([[-1.8611]])
torch.matmul(x,A)=tensor([[ 0.5824],
        [-2.8406]]), nb elem=2
b=tensor([-0.1281])
torch.matmul(x,A)+b=tensor([[ 0.4543],
        [-2.9687]])


In [47]:
# A minimal example of SGD (Stochastic Gradient Descent)
# without a Neural Network

import torch
import torch.nn as nn
import torch.optim as optim

N = 64 # amount of values inside the tensors

# Define 2 equivalent tensors x and y with a torch.Size([64, 1])
x0 = torch.randn(N, 1, requires_grad=False)
x = x0
y = x0

# Define the model parameters to optimize
A = torch.randn(1, 1, requires_grad=True) # size 1 x 1 (weights of the model) -> torch.Size([1, 1])
b = torch.randn(1, requires_grad=True) # Size 1 (biases of the model) -> torch.Size([1])

print("Initial values of A={}, b={}".format(A,b))

optimizer = optim.SGD([A, b], lr=1e-1) # Define SGD with [A, b] as parameters and learning rate to 1e-1

print("Learning rate={}".format(1e-1))

for t in range(20):
    print('-' * 50)
    optimizer.zero_grad() # Clean gradients of A and b (because they have requires_grad to True)
    # torch matmul -> If both arguments are 2-dimensional, the matrix-matrix product is returned.
    y_pred = torch.matmul(x, A) + b # Calculate a noisy predicted value -> (x * A) + b
    loss = ((y_pred - y) ** 2).mean() # Calculate loss value (y is the actual value)
    print("{} -> loss={}".format(t, loss.item())) # print loss value, need item() function to get it
    loss.backward() # Compute gradient of A and b with loss value
    print("A.grad={},b.grad={}".format(A.grad,b.grad))
    optimizer.step() # Update values of A and b by taking account of their gradient and the learning rate
    # A += -lr * A.grad  ; b += -lr * b.grad
    print("A={}, b={}".format(A,b))


Initial values of A=tensor([[-0.4984]], requires_grad=True), b=tensor([-0.1915], requires_grad=True)
Learning rate=0.1
--------------------------------------------------
0 -> loss=2.16462779045105
A.grad=tensor([[-2.8777]]),b.grad=tensor([-0.0906])
A=tensor([[-0.2106]], requires_grad=True), b=tensor([-0.1825], requires_grad=True)
--------------------------------------------------
1 -> loss=1.4158093929290771
A.grad=tensor([[-2.3196]]),b.grad=tensor([-0.1286])
A=tensor([[0.0214]], requires_grad=True), b=tensor([-0.1696], requires_grad=True)
--------------------------------------------------
2 -> loss=0.9280121326446533
A.grad=tensor([[-1.8709]]),b.grad=tensor([-0.1482])
A=tensor([[0.2084]], requires_grad=True), b=tensor([-0.1548], requires_grad=True)
--------------------------------------------------
3 -> loss=0.6095335483551025
A.grad=tensor([[-1.5098]]),b.grad=tensor([-0.1551])
A=tensor([[0.3594]], requires_grad=True), b=tensor([-0.1393], requires_grad=True)
--------------------------

In [48]:
# A simple test of gradient
# To proof the result of gradient

x = torch.ones(2, 2, requires_grad=True) # size 2 x 2 with all values equal to 1
y = x + 2  # size 2 x 2 with all values equal to 3
z = y * y * 2 # size 2 x 2 with all values equal to 18

out = z.mean() # mean is equal to 18 ! (18*4/4)
print("mean={}".format(out))

out.backward() # compute gradient of x

# Math demonstration :
# out = 1/4 sum of z(j) (for j from 1 to 4)
# d.out/d.x(i) = 1/4 sum(j)[d.z(j)/d.x(i)]  ==> partial derivative of dout with respect to x (i and j from 1 to 4)
# = 1/4 sum(j)[d.2*y(j)*y(j)/d.x(i)]
# = 1/4 sum(j)[ 4*y(j)*(d.y(j)/d.x(i))]
# = 1/4 sum(j)[4*(x(j)+2)*(d.(x(j)+2)/d.x(i))]
# = sum(j)[(x(j)+2)*(d.(x(j)+2)/d.x(i))]
# = x(i)+2    -> d.x(j)/d.x(i) = 0 if i not equal to j
# = 3         -> for x(i) = 1  => tensor x : size 2 x 2 with all 1 values

print("x grad={}".format(x.grad))

mean=18.0
x grad=tensor([[3., 3.],
        [3., 3.]])


In [49]:
# A minimal example of SGD (Stochastic Gradient Descent)
# with a Neural Network

import torch
import torch.nn as nn
import torch.optim as optim
#from torchsummary import summary  # pip install torchsummary

# Let's make some data for a linear regression.
A = 3.1415926
B = 2.7189351
error = 0.1
N = 100 # number of data points

# Data
input_data = torch.randn(N, 1)

# (noisy) Target values that we want to learn.
target = A * input_data + B + (torch.randn(N, 1) * error)

# Creating a model, making the optimizer, defining loss
model = nn.Linear(1, 1) 
# create a Neural Network Linear with in_features=1 and out_features=1 (nn.Linear(in_features,ou_features))
# Applies a linear transformation to the incoming x data: y = x*W^T + b
# Note that the weights W have shape (out_features, in_features) and biases b have shape (out_features).

# Verify model tensors parameters :
for name, param in model.named_parameters():
    print('name: ', name)
    print(type(param))
    print('param.shape: ', param.shape)
    print('param.requires_grad: ', param.requires_grad)
    print('=====')

# name:  weight
# <class 'torch.nn.parameter.Parameter'>
# param.shape:  torch.Size([1, 1])
# param.requires_grad:  True
# =====
# name:  bias
# <class 'torch.nn.parameter.Parameter'>
# param.shape:  torch.Size([1])
#param.requires_grad:  True
# =====

print("model weight={}, model bias={}".format(model.weight,model.bias))

#model_summary(model)

optimizer = optim.SGD(model.parameters(), lr=0.05)
loss_fn = nn.MSELoss()  # the mean squared error (squared L2 norm)

# Run training
nb_iter = 50
for _ in range(0, nb_iter):
    optimizer.zero_grad() # Clear gradient values of model parameters
    predictions = model(input_data)
    # forward input_data into the model
    # So multiply input_data to weight tensor parameter inside model
    # Sizes are : input_data -> torch.Size([100, 1]) ; weight -> torch.Size([1, 1])
    # torch.matmul(input_data,weight) -> torch.Size([100, 1])
    # If both arguments are at least 1-dimensional and at least one argument is N-dimensional (where N > 2), 
    # then a batched matrix multiply is returned
    # Then add bias tensor of size : torch.Size([1])
    # and get a prediction -> torch.Size([100, 1])
    loss = loss_fn(predictions, target) # calculate loss value
    loss.backward() # calculate gradient values
    optimizer.step() # update model parameters with gradient values

    print("-" * 50)
    print("error = {}".format(loss.item()))
    print("learned weight = {}".format(list(model.parameters())[0].data[0, 0]))
    print("learned bias = {}".format(list(model.parameters())[1].data[0]))
    

name:  weight
<class 'torch.nn.parameter.Parameter'>
param.shape:  torch.Size([1, 1])
param.requires_grad:  True
=====
name:  bias
<class 'torch.nn.parameter.Parameter'>
param.shape:  torch.Size([1])
param.requires_grad:  True
=====
model weight=Parameter containing:
tensor([[-0.9948]], requires_grad=True), model bias=Parameter containing:
tensor([0.7632], requires_grad=True)
--------------------------------------------------
error = 22.306852340698242
learned weight = -0.5600687861442566
learned bias = 0.9834200143814087
--------------------------------------------------
error = 17.810943603515625
learned weight = -0.17105355858802795
learned bias = 1.1788705587387085
--------------------------------------------------
error = 14.222236633300781
learned weight = 0.17709621787071228
learned bias = 1.3523228168487549
--------------------------------------------------
error = 11.35754680633545
learned weight = 0.4886828064918518
learned bias = 1.5062344074249268
--------------------------

In [50]:
# An other test with nn.Linear, to verify sizes

input_size = 8
output_size = 14
batch_size = 64

input = torch.FloatTensor(batch_size, input_size) # torch.Size([64, 8])

net = nn.Linear(input_size, output_size) # in_features=8, out_features=14
# net parameters -> W (weight) shape is (out_features, in_features) and b (biases) shape is (out_features)
# W=(14x8), W^T=(8x14), b=(14), input(64x8)
# output = input*W^T + b
# output=(64x14)
# rmq: operator + add tensor b to each line of tensor input*W^T

for name, param in net.named_parameters():
    print('name: ', name)
    print(type(param))
    print('param.shape: ', param.shape)
    print('param.requires_grad: ', param.requires_grad)
    print('=====')

# name:  weight
# <class 'torch.nn.parameter.Parameter'>
# param.shape:  torch.Size([14, 8])
# param.requires_grad:  True
# =====
# name:  bias
# <class 'torch.nn.parameter.Parameter'>
# param.shape:  torch.Size([14])
# param.requires_grad:  True

output = net(input)  # forward input into net

print("Output size:", output.size()) # torch.Size([64, 14])

name:  weight
<class 'torch.nn.parameter.Parameter'>
param.shape:  torch.Size([14, 8])
param.requires_grad:  True
=====
name:  bias
<class 'torch.nn.parameter.Parameter'>
param.shape:  torch.Size([14])
param.requires_grad:  True
=====
Output size: torch.Size([64, 14])


In [51]:
tensor1 = torch.randn(4, 5)
tensor2 = torch.randn(5)
print(tensor1)
print(tensor2)
r = tensor1 + tensor2
print(r)

tensor([[ 0.6247, -1.4768,  0.1176,  2.4309,  0.8171],
        [ 0.7873, -1.3760, -0.4580,  0.4971, -1.5577],
        [ 0.4515, -1.6608,  1.9961,  0.9986,  0.7098],
        [ 0.6303, -1.0195,  0.2721, -0.5018,  0.5399]])
tensor([ 3.0344, -0.0608,  0.2766, -0.6585,  0.1233])
tensor([[ 3.6592, -1.5376,  0.3942,  1.7723,  0.9404],
        [ 3.8217, -1.4368, -0.1814, -0.1615, -1.4344],
        [ 3.4859, -1.7217,  2.2727,  0.3400,  0.8331],
        [ 3.6647, -1.0804,  0.5488, -1.1603,  0.6632]])
